spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_CANDLE}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  datasource:
    url: ${POSTGRE_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul

kafka:
  consumer: ${KAFKA_CONSUMER_CANDLE}
  topic:
    candle: ${KAFKA_TOPIC_CANDLE}
    ticker: ${KAFKA_TOPIC_TICKER}

management:
  endpoints:
    web:
      base-path: /upbit-service
      exposure:
        include: health, info, prometheus